Certutil Detection:

  Event
  | where EventID == 1
  | extend raw_xml = tostring(EventData)
  | extend 
      Image = extract(@"<Data Name=""Image"">(.*?)</Data>", 1, raw_xml),
      CommandLine = extract(@"<Data Name=""CommandLine"">(.*?)</Data>", 1, raw_xml),
      ParentImage = extract(@"<Data Name=""ParentImage"">(.*?)</Data>", 1, raw_xml),
      User = tostring(extract(@"<Data Name=""User"">(.*?)</Data>", 1, raw_xml)
  | where Image has "certutil"
  | project TimeGenerated, Image, CommandLine, ParentImage, User

Scheduled Tasks detection:

  Event
  | where EventID == 1
  | extend raw_xml = tostring(EventData)
  | extend 
    Image = extract(@"<Data Name=""Image"">(.*?)</Data>", 1, raw_xml),
    CommandLine = extract(@"<Data Name=""CommandLine"">(.*?)</Data>", 1, raw_xml),
    ParentImage = extract(@"<Data Name=""ParentImage"">(.*?)</Data>", 1, raw_xml),
    User = extract(@"<Data Name=""User"">(.*?)</Data>", 1, raw_xml)
  | where Image endswith "schtasks.exe"
      and ParentImage has_any ("powershell.exe", "cmd.exe")
      and CommandLine has "create"
  | project TimeGenerated, Image, CommandLine, ParentImage, User

Procdump detection:

  Event
  | where EventID == 1
  | extend raw_xml = tostring(EventData)
  | extend 
    Image = extract(@"<Data Name=""Image"">(.*?)</Data>", 1, raw_xml),
    CommandLine = extract(@"<Data Name=""CommandLine"">(.*?)</Data>", 1, raw_xml),
    ParentImage = extract(@"<Data Name=""ParentImage"">(.*?)</Data>", 1, raw_xml),
    User = extract(@"<Data Name=""User"">(.*?)</Data>", 1, raw_xml)
  | where Image has "procdump"
  | project TimeGenerated, Image, CommandLine, ParentImage, User
